[build]
builder = "NIXPACKS"

[deploy]
runtime = "V2"
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[nixpacks]
build = "npm run prisma && npm run build"
start = "npm run start"